package tn.jobnest.gentretien.service;

import tn.jobnest.gentretien.model.Competence;
import tn.jobnest.gentretien.utils.MyDatabase;  // ← importe ton singleton

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class CompetenceService {

    private Connection cnx;

    public CompetenceService() {
        try {
            cnx = MyDatabase.getInstance().getConn();   // ← seule modification ici
        } catch (Exception e) {   // on garde Exception large comme avant
            System.err.println("❌ Erreur connexion DB");
            e.printStackTrace();
        }
    }

    // ================= AJOUTER =================
    public void ajouter(Competence c) {

        String sql = """
            INSERT INTO competence 
            (nom, categorie, description, niveau_requis, otp_secret)
            VALUES (?, ?, ?, ?, ?)
        """;

        try (PreparedStatement ps = cnx.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, c.getNom());
            ps.setString(2, c.getCategorie());
            ps.setString(3, c.getDescription());
            ps.setString(4, c.getNiveauRequis());
            ps.setString(5, c.getOtpSecret());

            ps.executeUpdate();

            // 🔥 IMPORTANT جداً: نرجّع ID المولّد من DB
            ResultSet rs = ps.getGeneratedKeys();
            if (rs.next()) {
                c.setIdCompetence(rs.getInt(1));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // ================= GET ALL =================
    public List<Competence> getAll() {

        List<Competence> list = new ArrayList<>();
        String sql = "SELECT * FROM competence";

        try (Statement st = cnx.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {

                list.add(new Competence(
                        rs.getInt("id_competence"),
                        rs.getString("nom"),
                        rs.getString("categorie"),
                        rs.getString("description"),
                        rs.getString("niveau_requis"),
                        rs.getString("otp_secret")
                ));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return list;
    }

    public Competence findOrCreate(String skillName) {

        try {

            String cleaned = skillName.trim().toLowerCase();

            // 1️⃣ نبحث هل موجودة
            String select = "SELECT * FROM competence WHERE LOWER(nom) = ?";

            PreparedStatement ps = cnx.prepareStatement(select);
            ps.setString(1, cleaned);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // موجودة → نرجعها
                Competence c = new Competence();
                c.setIdCompetence(rs.getInt("id_competence"));
                c.setNom(rs.getString("nom"));
                c.setCategorie(rs.getString("categorie"));
                c.setDescription(rs.getString("description"));
                c.setNiveauRequis(rs.getString("niveau_requis"));
                return c;
            }

            // 2️⃣ مش موجودة → نخلقها 🔥
            String insert = "INSERT INTO competence (nom, categorie, description, niveau_requis) VALUES (?,?,?,?)";

            PreparedStatement ps2 = cnx.prepareStatement(insert, Statement.RETURN_GENERATED_KEYS);
            ps2.setString(1, skillName);
            ps2.setString(2, "technique");
            ps2.setString(3, "Auto generated by AI");
            ps2.setString(4, "intermediaire");

            ps2.executeUpdate();

            ResultSet generatedKeys = ps2.getGeneratedKeys();
            if (generatedKeys.next()) {
                int id = generatedKeys.getInt(1);

                Competence newC = new Competence();
                newC.setIdCompetence(id);
                newC.setNom(skillName);
                newC.setCategorie("technique");
                newC.setDescription("Auto generated by AI");
                newC.setNiveauRequis("intermediaire");

                return newC;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return null;
    }

    // ================= SUPPRIMER =================
    public void supprimer(int id) {

        String sql = "DELETE FROM competence WHERE id_competence=?";

        try (PreparedStatement ps = cnx.prepareStatement(sql)) {

            ps.setInt(1, id);
            ps.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // ================= MODIFIER =================
    public void modifier(Competence c) {

        String sql = """
            UPDATE competence
            SET nom=?, 
                categorie=?, 
                description=?, 
                niveau_requis=?, 
                otp_secret=?
            WHERE id_competence=?
        """;

        try (PreparedStatement ps = cnx.prepareStatement(sql)) {

            ps.setString(1, c.getNom());
            ps.setString(2, c.getCategorie());
            ps.setString(3, c.getDescription());
            ps.setString(4, c.getNiveauRequis());
            ps.setString(5, c.getOtpSecret());
            ps.setInt(6, c.getIdCompetence());

            ps.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}